---
title: "SI_quant"
Horowitz, Mekler, Schneider, Frank, etc. 
Analyses for Scalar Implicature, Give-Quantifier, and DCCS
---

Set up Rmd parameters
```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(cache=TRUE, message=FALSE, warning=FALSE)
```

Preliminaries.
```{r}
rm(list=ls())
library(ggplot2)
library(reshape)
library(entropy)
library(pscl)
library(dplyr)
library(stringr)
library(tidyr)
library(markdown)
library(directlabels)
library(magrittr)
library(bootstrap)
library(RMySQL)
library(RCurl)

theme_set(theme_bw())
```

---
SI
---

```{r}

d1 <- read.csv("..//data/SI_coding.csv")

d2=melt.data.frame(d1,c("sub_ID","experimenter","test_age","condition", "order", "training"),c("carrot", "hat", "cookies", "trains", "cats", "purses",  "keys", "shirts", "breads", "horses", "bears", "frogs", "plates", "books", "elephants", "lamps", "bananas", "butterflies", 
"carrot_condition", "hat_condition", "cookies_condition", "trains_condition", "cats_condition", "purses_condition",  "keys_condition", "shirts_condition", "breads_condition", "horses_condition", "bears_condition", "frogs_condition", "plates_condition", "books_condition", "elephants_condition", "lamps_condition", "bananas_condition", "butterflies_condition", 
"carrot_type", "hat_type", "cookies_type", "trains_type", "cats_type", "purses_type",  "keys_type", "shirts_type", "breads_type", "horses_type", "bears_type", "frogs_type", "plates_type", "books_type", "elephants_type", "lamps_type", "bananas_type", "butterflies_type"))


#making a respectable df  
data <- d2[1:702,] 
data$condition <- d2$value[703:1404]
data$type <- d2$value[1405:2106]
names(data)[7] <- "item"
names(data)[8] <- "SI_correct"
data$correct <- data$SI_correct==1

#filtering out unnecessary things, adding agesplit
data %<>%
  filter(sub_ID != "", correct != "NA") %>%
  mutate(agesplit = cut(test_age, breaks=c(3, 3.5, 4, 4.5, 5)))%>%
  mutate(split_2 = cut(test_age, breaks = c(3, 4, 5)))%>%
  filter(agesplit != "NA")

data_si <- data
data_si$test <- "Scalar Implicature"
```

SI analyses 
```{r}
#number of kids in each age group
num_kids <- data %>%
  select(sub_ID, agesplit) %>%
  distinct() %>%
  group_by(agesplit)%>%
  summarize(n=n())


#accuracy by age group in different trials 
agg.data <- aggregate(data$correct, list(data$type, data$agesplit), FUN=sum)
agg.data.len <- aggregate(data$correct, list(data$type, data$agesplit), FUN=length)
agg.data$x <- agg.data$x 
agg.data.len$x <- agg.data.len$x 

names(agg.data) <- c("type", "agesplit", "correct")
agg.data$total <- agg.data.len$x
agg.data$prop.corr <- agg.data$correct / agg.data$total

agg.data$q <- 1 - agg.data$prop.corr
agg.data$err <- sqrt((agg.data$prop.corr * agg.data$q) / agg.data$total)

dodge <- position_dodge(width=0.9) 
limits <- aes(ymax = prop.corr + err, ymin=prop.corr - err) 

#plot
quartz()
ggplot(data = agg.data, 
       aes(x=type, y=prop.corr, fill=agesplit)) +
  geom_bar(stat="identity", position = position_dodge())  + geom_errorbar(limits, position=dodge)+
  ylab("Proportion correct") + 
  xlab("Trial Type") +
  scale_fill_brewer(palette="Set1")
```

---
GQ analyses 
---

```{r}
#read in and establish dataframe
d1 <- read.csv("..//data/GQ_coding.csv")

d2=melt.data.frame(d1,c("sub_ID","experimenter", "test_age","condition", "training"),c("X1_condition", "X2_condition", "X3_condition", "X4_condition", "X5_condition", "X6_condition",  "X7_condition", "X8_condition", "X1_given", "X2_given", "X3_given", "X4_given", "X5_given", "X6_given",  "X7_given", "X8_given"))

#making a respectable df  
data <- d2[1:320,] 
data$num_given <- d2$value[321:640]
names(data)[6] <- "trial"
names(data)[7] <- "prompt"


#filtering data, creating age breaks
data %<>%
  filter(sub_ID != "", num_given != "N/A") %>%
  mutate(agesplit = cut(test_age, breaks=c(3, 3.5, 4, 4.5, 5)))%>%
  mutate(split_2 = cut(test_age, breaks = c(3, 4, 5)))%>%
  filter(agesplit != "NA", num_given != "0 (8 oranges)", num_given != "0 (8 bananas)", num_given != "0 (8 strawberries)")

#this is because num_given is a factor - need to change to a number
data$num_given <- as.character(data$num_given)
data$num_given <- as.numeric(data$num_given)

data_gq <- data
data_gq$test <- "Give-Quantifier"
```

Average given for each prompt by age group 
```{r}
agg.data <- aggregate(data$num_given, list(data$prompt, data$agesplit), FUN=mean)
agg.data.sd <- aggregate(data$num_given, list(data$prompt, data$agesplit), FUN=sd)

names(agg.data) <- c("prompt", "agesplit", "num_given")
agg.data$sd <- agg.data.sd$x

##establish limits
limits <- aes(ymax = num_given + sd, ymin=num_given - sd) 

#plot
quartz()
ggplot(data = agg.data, 
       aes(x=prompt, y=num_given, fill=agesplit)) +
  geom_bar(stat="identity", position = position_dodge())  + geom_errorbar(limits, position=dodge)+
  ylab("Mean num given") + 
  xlab("Quantifier prompt") +
  scale_fill_brewer(palette="Set1")
```

Histogram of responses, faceted by age group
```{r}
hist_data <- data %>%
  group_by(split_2, prompt, num_given)%>%
  summarise(n = n()) %>%
  group_by(split_2, prompt) %>%
  mutate(n.total = sum(n), prop = n/n.total)


quartz()
ggplot(data = hist_data, aes(x = num_given, y = prop, fill = split_2)) + geom_bar(stat = "identity", position = position_dodge()) + xlab("Number Given") + ylab("Count of kids giving number") + facet_wrap(~prompt) + scale_fill_brewer(palette="Set1")

```

---
DCCS analyses
---

Read in dataframe
```{r}
d1 <- read.csv("..//data/DCCS_coding.csv")

d2=melt.data.frame(d1,c("sub_ID","experimenter","test_age","condition", "order"),c("pre_1", "pre_2", "pre_3", "pre_4", "pre_5", "pre_6",  "post_1", "post_2", "post_3", "post_4", "post_5", "post_6"))

#filtering data, creating age breaks
data <- d2 %>%
  filter(sub_ID != "") %>%
  mutate(agesplit = cut(test_age, breaks=c(3, 3.5, 4, 4.5, 5)), split_2 = cut(test_age, breaks = c(3, 4, 5)))

names(data)[6] <- "trial_type"
names(data)[7] <- "DCCS_correct"

data_dccs <- data
data_dccs$test <- "DCCS"
  
```

Accuracy on DCCS task
```{r}
agg.data <- aggregate(data$correct, list(data$trial_type, data$agesplit), FUN=sum)
agg.data.len <- aggregate(data$correct, list(data$trial_type, data$agesplit), FUN=length)
agg.data$x <- agg.data$x 
agg.data.len$x <- agg.data.len$x 

names(agg.data) <- c("trial_type", "agesplit", "correct")
agg.data$total <- agg.data.len$x
agg.data$prop.corr <- agg.data$correct / agg.data$total

agg.data$q <- 1 - agg.data$prop.corr
agg.data$err <- sqrt((agg.data$prop.corr * agg.data$q) / agg.data$total)

dodge <- position_dodge(width=0.9) 
limits <- aes(ymax = prop.corr + err, ymin=prop.corr - err) 

#plot
quartz()
ggplot(data = agg.data, 
       aes(x=trial_type, y=prop.corr, fill=agesplit)) +
  geom_bar(stat="identity", position = position_dodge())  + geom_errorbar(limits, position=dodge)+
  ylab("Proportion correct") + 
  xlab("Trial Type") +
  scale_fill_brewer(palette="Set1") + facet_wrap(~agesplit)
```


---
Stats
---


To do: Simple correlations between tasks, regressions


